name: Test

on:
  workflow_call:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  push:
    branches:
      - main
      - release-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: nscloud-ubuntu-20.04-amd64-4x16
    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          enable-cache: true

      - name: Setup devbox
        run: devbox run -- echo "done!"

      - name: Load devbox shellenv
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.3

      - name: Set up Go tool cache
        uses: actions/cache@v4.0.0
        with:
          path: ~/.devbox/go
          key: devbox-go-tools.cache-${{ runner.os }}-${{ runner.arch }}

      - name: Run tests
        run: make test
